# 容器覆盖配置
# - 仅在容器独立使用时会自动加载本配置

services:
  xray:
    network_mode: !reset null
    depends_on: !reset null  # 如果使用 podman-compose，则需要 v1.5.0+

    volumes: !override
      - ./templates/server:/usr/local/etc/templates:ro # 多配置模板 - 服务端
      # - ./templates/client:/usr/local/etc/templates:ro # 多配置模板 - 客户端
      - ./v2ray:/usr/share/xray:ro  # 本地卷 - 自定义地理数据文件
      - ./log:/var/log/xray:rw  # 本地卷 - 日志目录

      - ./.env.warp:/usr/local/etc/.env.warp:ro

    dns:
      - 1.1.1.1
      - 8.8.8.8
    ports:  # xray 独立运行时的端口，服务端/客户端按需配置即可
      - "10088:10088"
