name: '📦 Docker Build and Push'

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-build.yml'

  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Manual image tag to build and push'
        required: true

  repository_dispatch:
    types: [release-auto]

permissions: read-all

jobs:
  build:
    uses: Lanrenbang/.github/.github/workflows/reusable-docker-build.yml@main
    permissions:
      contents: read
      packages: write
    secrets:
      dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
