name: '🤖 Upstream Watcher'

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  check:
    uses: Lanrenbang/.github/.github/workflows/reusable-upstream-watcher.yml@main
    with:
      repositories: |
        [
          {"repo": "Lanrenbang/envwarp"},
          {"repo": "XTLS/Xray-core"}
        ]
    secrets:
      bot_pat: ${{ secrets.BOT_PAT }}
